### ISSUE TITLE
PyPaint Errors

### ISSUE THREAD

**Issue by djecken** [adafruit/Adafruit_Learning_System_Guides#751]
@dastels Hiya, I'm testing this out. Running PyPaint on PyGamer using circuit python 4.0.2 with latest libraries from bundle.

- Analog joystick is inverted when moving cursor
- Pressing A button triggers error, exits program and loads console on screen.
- From console: cursorcontrol.py, Line 177, "group" object has no attribute "remove"

**Comment by djecken** [comment]
Just tested **PyBadge** with circuit python **4.0.2** getting same errors on **Line 177,** in hidden attributeError: 'group' object has no attribute 'remove'.

**Comment by tannewt** [comment]
Please try it with the Beta. I believe that is when remove was added.

**Comment by dastels** [comment]
As Scott said, use the latest beta.

**Comment by djecken** [comment]
confirmed works with 4.1.0 beta, yay!
